<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blogs = [
            [
                'title' => 'Oppo Reno 11 Series Launched in Pakistan; 120Hz OLED, Advance Cameras, ColorOS 14',
                'content' => "After extensive build-up on social media platforms, Oppo has officially introduced its highly anticipated Reno 11 series in Pakistan. The lineup includes Oppo Reno 11 5G and Reno 11F 5G, tuned with premium specifications, aesthetic design language, great cameras, and much more. Here's a debrief on all their specialties. Starting with the Oppo Reno 11 5G, the device brings a striking 6.7-inch OLED display with a smooth 120Hz refresh rate and HDR 10+ support, delivering lifelike colors. Powered by a MediaTek Dimensity 7050 processor, 12GB of LPDDR4x RAM, and 256GB of UFS 2.2 storage, the Reno 11 5G has exceptional performance. Atop the screen, the punch-hole cutout houses a 32MP selfie camera. Powering the device is a 5000mAh battery supporting rapid 67W SuperVOOC charging, claiming a full top-up in approximately 45 minutes. The Reno 11 5G is available in four colors: Green, Rock Grey, Pearl White, and Rock Grey, making it suitable for various preferences.
                The handset’s rear camera setup includes a 50MP alpha sensor, an 8MP ultrawide sensor, and a 32MP telephoto shooter, ensuring impressive photography in numerous scenarios. With all these specs combined, the Reno 11 5G fits the mid-range class of devices perfectly at Rs 129999/-. On the other hand, the Oppo Reno 11F features a 6.7-inch 120Hz FullHD+ flat OLED display with Panda Glass protection and HDR10+ support. The device offers seamless performance using ColorOS 14, equipped with a Dimensity 7050 SoC and 8GB of RAM. Its rear triple camera setup comprises a 64MP primary camera with OIS, an 8MP ultrawide camera, and a 2MP macro lens, catering to various photography needs. With 256GB of onboard storage, the device allows expandable memory of up to 2TB via microSD card. The device is available in Palm Green, Ocean Blue, and Coral Purple variants. Fueling the Reno11 F is a 5,000mAh battery supported by 67W charging, touted to provide four years of longevity and a full charge in just 48 minutes. The Reno 11F 5G, in a single 8+256GB configuration, costs only Rs 79999/-.",
                'user_id' => 1
            ],
            [
                'title' => 'nfinix Hot 40i (8/256GB) gets more Wallet-friendly in Pakistan with Rs 4,000 Discount',
                'content' => "Infinix has announced a notable price cut for its Hot 40i (8/256GB variant) in Pakistan, dropping the retail cost from Rs 36,000 to Rs 31,999. It means a generous discount of Rs 4,000 awaits prospective buyers. The brand’s cutback on the price aims to make the Infinix Hot 40i more accessible to consumers. As far as its specs go, the Infinix Hot 40i impresses with its 6.56-inch display, featuring a speedy 90Hz refresh rate and HD+ resolution. Powered by a modest MediaTek Helio G88 chipset, the device ensures seamless performance to keep up with users' daily tasks and activities.Running on the latest Android 13, the Hot 40i delivers an intuitive user interface, adding to its usability and functionality. Casual photographers will appreciate the device's 50MP rear sensor, accompanied by an AI sidekick for mapping depth in portrait shots. On the front of this latest Infinix budget mobile, a high-resolution 32MP selfie camera promises Instagram-worthy shots, while a side-mounted fingerprint sensor prioritizes user privacy and security. Beneath its sleek exterior, the Infinix Hot 40i houses a substantial 5,000mAh battery, offering extended longevity for uninterrupted usage. With 18W fast charging support, users can quickly replenish their devices when needed. Despite its robust battery, the device maintains a slim profile, measuring 8.3mm thin and weighing a mere 190 grams.",
                'user_id' => 1
            ],
            [
                'title' => 'Infinix NOTE 40 Series: Retail Box Leaks suggest Potential Charging Advancements',
                'content' => "As the tech world eagerly awaits the launch of Infinix's latest innovation, Infinix NOTE 40 rumors have started to surface, giving an alluring hint into its cutting-edge technology including a surprising 20W Wireless MagCharge. Further we can also see a Magcharge logo by which we can assume it to be included within the retail unit. Though it is expected to be available in Pakistan starting April 2024.We are abuzz with anticipation surrounding the imminent launch of the Infinix Note 40 Series. Leaked images of the NOTE 40 Pro retail box have ignited speculation about groundbreaking advancements in the realm of smartphone charging technology. While the full picture remains under wraps until the official unveiling, these early glimpses hint at a potential game-changer. Notably, the box suggests the inclusion of both a 20W wireless MagCharge and a 70W wired All-Round Fast Charging system.
                We are unclear whether these functionalities will be fully realized through in-box accessories or if they have to be bought separately.",
                'user_id' => 1
            ],
            [
                'title' => 'Infinix Note 30 Pro (8/256GB) Seeks Attention with 10,000 PKR Discount in Pakistan',
                'content' => "Infinix Note 30 Pro's retail price in Pakistan has been slashed from Rs 63,000 to Rs 52,999, presenting a substantial discount of Rs 10,000 for consumers. The device stands out with its performance and impressive charging technology, boasting 68W fast charging, including reverse and wireless options.Featuring an upgraded 6.67-inch AMOLED panel, the Note 30 Pro offers a smooth 120Hz refresh rate and ultra-responsive 360Hz touch sampling rate, enhancing the visual experience for users. Packed tightly with IP53 water and dust resistance, its chassis has flat borders and a bevel-less design.  While maintaining a powerful 108MP primary camera, the device upgrades its selfie shooter to a 32MP sensor, accompanied by a front-facing flash for improved selfies. Additionally, the Pro variant includes a vapor chamber cooling solution, keeping the temps low while gaming.Under the hood, the Infinix new Note mobile mounts an octa-core CPU configuration comprising 2 x 2.2 GHz Cortex-A76 cores and 6 x 2.0 GHz Cortex-A55 cores. The chipset is MediaTek’s Helio G99, built on 6nm technology, and promises enhanced performance and efficiency.Graphics are handled by the Mali-G57 MC2 GPU, ensuring smooth visuals and seamless multitasking. For audio, the Note 30 Pro elevates the experience with dual JBL speakers, ensuring immersive sound quality. It also incorporates NFC functionality and retains the traditional 3.5mm audio jack.",
                'user_id' => 1
            ],
            [
                'title' => 'Infinix NOTE 40 series defies norms with 20W MagCharge technology now introduced globally',
                'content' => "Infinix, a trendy tech brand crafted for young consumers, is thrilled to announce the latest addition to its product lineup: the NOTE 40 Series. This remarkable series comprises the NOTE 40, NOTE 40 Pro, NOTE 40 Pro 5G, and the most advanced model, the NOTE 40 Pro+ 5G. By setting a new benchmark for fast charging, Infinix showcases its All-Round HyperSpeed Lab to unveil these groundbreaking products at the F1 Sepang International Circuit in Malaysia, igniting the exhilaration that emerges when speed and technology converge.The NOTE 40 Series represents a significant advancement in Infinix’s All-Round FastCharge 2.0 technology, introducing innovations such as 100W Multi-Speed FastCharge, Wireless MagCharge, and a self-developed chip that supports multi-function charging modes. Additionally, the series features a vibrant and responsive 3D curved 120Hz AMOLED display and a robust 108MP super-zoom camera system with OIS support. Infinix has also incorporated AI enhancements like Active Halo AI lighting and partnered with Sound by JBL, ensuring an unparalleled level of performance and efficiency.

                “The Infinix NOTE 40 Series represents a significant advancement in charging technology, transforming the power experience. With our proprietary Cheetah X1 chip at its core, All-Round FastCharge has entered a new era, offering features like multi-speed charging and extreme temperature charging. We've also introduced the innovative MagCharge accessory kit, providing a seamless charging ecosystem for users. These advancements unlock the full potential of the NOTE 40 Series, enabling users to stay powered up all day, in any scenario, and in any weather, ” Weiqi Nie, Product Director at Infinix.The NOTE 40 Series introduces All-Round FastCharge 2.0 technology, powered by Infinix’s first self-developed Cheetah X1 chip. This chip integrates high-precision power detection, secure voltage detection, and versatile scene support, ensuring exceptional charging efficiency and diverse capabilities. The NOTE 40 Pro+ 5G supports 100W Multi-Speed FastCharge, reaching 50% in just 8 minutes in hyper mode. It also offers low-temp mode and smart mode for tailored charging. The series boasts high-density batteries, enduring 1,600 full cycles while retaining 80% energy. Wireless charging is upgraded to 20W Wireless Magcharge, surpassing its class.

                The lineup includes the Infinix MagKit for a convenient magnetic charging experience, including the phone case MagCase, magnetic charging pad MagPad, and magnetic power bank MagPower. Extreme-Temp Tech ensures reliable charging down to -20 °C, ideal for snowy environments. Bypass Charging 2.0 filters current to supply power directly to the motherboard during intense gaming session or watching videos, preventing overheating. Reverse charging allows sharing power with other devices wired or wirelessly at speeds up to 10W. PD3.0 protocol support enables charging laptops with the phone’s charger, eliminating the need for multiple chargers.
                
                The Pro Series is inspired by cityscape aesthetics, featuring a stunning 55° curved display enhanced with durable Corning® Gorilla® Glass for an elegant and sturdy feel. The NOTE 40 boasts a flat display with an ultra-narrow bezel using the unibody MDA(metal device antenna) design, which hides the antenna into the frame. The 120Hz AMOLED display offers a 1080P resolution and a peak brightness of 1300 nits, ensuring enhanced visibility in all lighting conditions. TÜV Rheinland certification for anti-blue light eye protection and a high PWM Dimming rate of 2160Hz provides a flicker-free experience, enhancing visual comfort.
Infinix’s new ‘Active Halo’ feature is another standout, merging AI and design. It brings the NOTE 40 Series to life with lifelike light pulsations on the phone’s camera module. The light display changes based on various activities such as receiving calls, and notifications, playing games or music, charging the device, or using the voice assistant, Folax.The NOTE 40 Series offers enhanced camera functionality for mobile photographers and social media content creators. It features advanced in-sensor zoom technology, utilizing its impressive 108MP main camera to capture long-distance moments with 3x Lossless Superzoom, maintaining image clarity and details. The Pro series includes Optical Image Stabilization (OIS) technology, reducing camera shake for sharper and more stable shots.

Users can simultaneously record from the 32 MP front and rear cameras, capturing events or interviews from different perspectives using Dual Video mode. They can also leverage editing features like Vlog Clipper to create engaging vlog content for social media. The NOTE 40 Series is a valuable tool for creative enthusiasts looking to enhance their mobile photography and storytelling abilities.The NOTE 40 Series introduces the Dimensity 7020 and Helio G99 Ultimate chipset, utilizing cutting-edge 6nm processes for energy efficiency and high performance. These chipsets are enhanced by AI features on XOS 14, including Folax, Ask AI, and AI wallpaper generator, enhancing creativity and productivity.",
                'user_id' => 1
            ],
        ];

        foreach ($blogs as $blog) {
            \App\Models\Blog::create($blog);
        }
    }
}
