<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MobileComparisonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $comparisons = [
            [
                'image' => 'https://www.whatmobile.com.pk/admin/images/Xiaomi/XiaomiRedmiNote10Pro-b.jpg',
                'name' => 'Redmi Note 10 Pro',
                'price' => 'Rs. 50,999',
                'release_date' => '2021, March 04',
                'sim_support' => 'Dual SIM',
                'operating_system' => 'Android 11, MIUI 12',
                'phone_weight' => '192 g',
                'phone_dimensions' => '164.5 x 76.2 x 8.1 mm',
                'screen_size' => '6.67 inches',
                'screen_resolution' => '1080 x 2400 pixels',
                'screen_type' => 'Super AMOLED, 120Hz, HDR10, 450 nits (typ)',
                'screen_protection' => 'Corning Gorilla Glass 5',
                'internal_memory' => '64GB 6GB RAM, 128GB 6GB RAM, 128GB 8GB RAM',
                'ram' => '64GB 6GB RAM, 128GB 6GB RAM, 128GB 8GB RAM',
                'card_slot' => 'microSDXC (dedicated slot)',
                'processor' => 'Qualcomm SM7150 Snapdragon 732G (8 nm)',
                'gpu' => 'Adreno 618',
                'battery' => 'Li-Po 5020 mAh, non-removable',
                'front_camera' => '16 MP, f/2.5, (wide), 1/3.06", 1.0µm',
                'front_flash' => 'LED flash',
                'front_video_recording' => '4K@30fps, 1080p@30/60/120fps, 720p@960fps',
                'back_camera' => '108 MP, f/1.9, 26mm (wide), 1/1.52", 0.7µm, dual pixel PDAF',
                'back_flash' => 'LED flash',
                'back_video_recording' => '4K@30fps, 1080p@30/60/120',
                'bluetooth' => '5.1, A2DP, LE',
                '3G' => 'HSDPA 850 / 900 / 2100',
                '4G/LTE' => '1, 3, 5, 8, 40, 41',
                '5G' => '1, 3, 5, 8, 40, 41',
                'radio' => 'FM radio, recording',
                'wifi' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',
                'nfc' => 'Yes',
                'is_new' => true,
            ],
            // realme gt
            [
                'image' => 'https://www.whatmobile.com.pk/admin/images/Realme/RealmeGT-b.jpg',
                'name' => 'Realme GT',
                'price' => 'Rs. 74,999',
                'release_date' => '2021, March 04',
                'sim_support' => 'Dual SIM',
                'operating_system' => 'Android 11, Realme UI 2.0',
                'phone_weight' => '186 g',
                'phone_dimensions' => '158.5 x 73.3 x 8.4 mm',
                'screen_size' => '6.43 inches',
                'screen_resolution' => '1080 x 2400 pixels',
                'screen_type' => 'Super AMOLED, 120Hz, HDR10+, 1000 nits (peak)',
                'screen_protection' => 'Corning Gorilla Glass 5',
                'internal_memory' => '128GB 8GB RAM, 256GB 12GB RAM',
                'ram' => '128GB 8GB RAM, 256GB 12GB RAM',
                'card_slot' => 'No',
                'processor' => 'Qualcomm SM8350 Snapdragon 888 5G (5 nm)',
                'gpu' => 'Adreno 660',
                'battery' => 'Li-Po 4500 mAh, non-removable',
                'front_camera' => '16 MP, f/2.5, 26mm (wide), 1/3.0", 1.0µm',
                'front_flash' => 'No',
                'front_video_recording' => '4K@30/60fps, 1080p@30/60/480fps, gyro-EIS',
                'back_camera' => '64 MP, f/1.8, 26mm (wide), 1/1.73", 0.8µm, PDAF',
                'back_flash' => 'LED flash',
                'back_video_recording' => '4K@30/60fps, 1080p@30/60/480fps, gyro-EIS',
                'bluetooth' => '5.2, A2DP, LE',
                '3G' => 'HSDPA 850 / 900 / 2100',
                '4G/LTE' => '1, 3, 5, 8, 38, 40, 41',
                '5G' => '1, 3, 5, 8, 38, 40, 41',
                'radio' => 'No',
                'wifi' => 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot',
                'nfc' => 'Yes',
                'is_new'=> false,
            ],

            //samsung a52
            [
                'image' => 'https://www.whatmobile.com.pk/admin/images/Samsung/SamsungGalaxyA52-b.jpg',
                'name' => 'Samsung Galaxy A52',
                'price' => 'Rs. 57,999',
                'release_date' => '2021, March 04',
                'sim_support' => 'Hybrid Dual SIM',
                'operating_system' => 'Android 11, One UI 3.1',
                'phone_weight' => '189 g',
                'phone_dimensions' => '159.9 x 75.1 x 8.4 mm',
                'screen_size' => '6.5 inches',
                'screen_resolution' => '1080 x 2400 pixels',
                'screen_type' => 'Super AMOLED, 90Hz, 800 nits (HBM)',
                'screen_protection' => 'Corning Gorilla Glass 5',
                'internal_memory' => '128GB 6GB RAM, 128GB 8GB RAM, 256GB 8GB RAM',
                'ram' => '128GB 6GB RAM, 128GB 8GB RAM, 256GB 8GB RAM',
                'card_slot' => 'microSDXC (uses shared SIM slot)',
                'processor' => 'Qualcomm SM7125 Snapdragon 720G (8 nm)',
                'gpu' => 'Adreno 618',
                'battery' => 'Li-Po 4500 mAh, non-removable',
                'front_camera' => '32 MP, f/2.2, 26mm (wide), 1/2.8", 0.8µm',
                'front_flash' => 'No',
                'front_video_recording' => '4K@30fps, 1080p@30/120fps; gyro-EIS',
                'back_camera' => '64 MP, f/1.8, 26mm (wide), PDAF',
                'back_flash' => 'LED flash',
                'back_video_recording' => '4K@30fps, 1080p@30/120fps; gyro-EIS',
                'bluetooth' => '5.0, A2DP, LE',
                '3G' => 'HSDPA 850 / 900 / 1900 / 210',
                '4G/LTE' => '1, 2, 3, 4, 5, 7, 8, 12, 17, 20, 26, 28, 38, 40, 41, 66',
                '5G' => 'No',
                'radio' => 'FM radio',
                'wifi' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',
                'nfc' => 'Yes',
                'is_new' => false,
            ],

            //tecno spark 20 pro plus
            [
                'image' => 'https://www.whatmobile.com.pk/admin/images/Tecno/TecnoSpark7Pro-b.jpg',
                'name' => 'Tecno Spark 7 Pro',
                'price' => 'Rs. 21,999',
                'release_date' => '2021, March 04',
                'sim_support' => 'Dual SIM',
                'operating_system' => 'Android 11, HIOS 7.5',
                'phone_weight' => '193 g',
                'phone_dimensions' => '164.9 x 76.2 x 8.8 mm',
                'screen_size' => '6.6 inches',
                'screen_resolution' => '720 x 1600 pixels',
                'screen_type' => 'IPS LCD',
                'screen_protection' => 'No',
                'internal_memory' => '64GB 4GB RAM, 128GB 4GB RAM',
                'ram' => '64GB 4GB RAM, 128GB 4GB RAM',
                'card_slot' => 'microSDXC (dedicated slot)',
                'processor' => 'Mediatek Helio G80 (12 nm)',
                'gpu' => 'Mali-G52 MC2',
                'battery' => 'Li-Po 5000 mAh, non-removable',
                'front_camera' => '8 MP, f/2.0, (wide)',
                'front_flash' => 'Dual-LED flash',
                'front_video_recording' => '1080p@30fps',
                'back_camera' => '48 MP, f/1.8, (wide), PDAF',
                'back_flash' => 'Quad-LED flash',
                'back_video_recording' => '1080p@30fps',
                'bluetooth' => '5.0, A2DP, LE',
                '3G' => 'HSDPA 850 / 900 / 2100',
                '4G/LTE' => '1, 3, 5, 8, 38, 40, 41',
                '5G' => 'No',
                'radio' => 'FM radio',
                'wifi' => 'Wi-Fi 802.11 b/g/n, hotspot',
                'nfc' => 'No',
                'is_new' => true,
            ],
            //xaoimi mi 11 lite
            [
                'image' => 'https://www.whatmobile.com.pk/admin/images/Xiaomi/XiaomiMi11Lite-b.jpg',
                'name' => 'Xiaomi Mi 11 Lite',
                'price' => 'Rs. 41,999',
                'release_date' => '2021, March 04',
                'sim_support' => 'Hybrid Dual SIM',
                'operating_system' => 'Android 11, MIUI 12',
                'phone_weight' => '157 g',
                'phone_dimensions' => '160.5 x 75.7 x 6.8 mm',
                'screen_size' => '6.55 inches',
                'screen_resolution' => '1080 x 2400 pixels',
                'screen_type' => 'AMOLED, 1B colors, HDR10, 90Hz, 500 nits (typ)',
                'screen_protection' => 'Corning Gorilla Glass 5',
                'internal_memory' => '64GB 6GB RAM, 128GB 6GB RAM',
                'ram' => '64GB 6GB RAM, 128GB 6GB RAM',
                'card_slot' => 'microSDXC (uses shared SIM slot)',
                'processor' => 'Qualcomm SM7150 Snapdragon 732G (8 nm)',
                'gpu' => 'Adreno 618',
                'battery' => 'Li-Po 4250 mAh, non-removable',
                'front_camera' => '16 MP, f/2.5, 25mm (wide), 1/3.06", 1.0µm',
                'front_flash' => 'No',
                'front_video_recording' => '1080p@30fps',
                'back_camera' => '64 MP, f/1.8, 26mm (wide), 1/1.97", 0.7µm, PDAF',
                'back_flash' => 'LED flash',
                'back_video_recording' => '4K@30fps, 1080p@30/60/120fps',
                'bluetooth' => '5.1, A2DP, LE',
                '3G' => 'HSDPA 850 / 900 / 2100',
                '4G/LTE' => '1, 3, 5, 7, 8, 20, 28, 38, 40, 41',
                '5G' => 'No',
                'radio' => 'No',
                'wifi' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot',
                'nfc' => 'Yes',
                'is_new' => false,
            ],
        ];

        foreach ($comparisons as $comparison) {
            \App\Models\Mobile::create($comparison);
        }
    }
}
